[profile.default]
src = "src"
out = "out"
libs = ["lib"]

optimizer = true
optimizer_runs = 1_000_000
solc_version = "0.8.20"

fs_permissions = [{ access = "read-write", path = "./deployments"}, { access = "read", path = "./"}]

[fmt]
line_length = 120
wrap_comments = true
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
